spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.show-sql=false

logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO

spring.web.error.include-message=never
spring.web.error.include-binding-errors=never