spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.config.import=optional:file:.env[.properties]

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework=ERROR
logging.level.org.springframework.security=TRACE

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
