name: CD

on: 
  push:
    branches:
      - main

permissions: 
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yinglottus/api-lottus

jobs:
  
  docker:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Give execute permission for mvnw
        run: chmod +x mvnw

      - name: Executar testes
        run: ./mvnw verify -B

      - name: Login no ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir imagem Docker
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Enviar imagem Docker para o ghcr.io
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} 
    

